### ISSUE TITLE
No error provided when setting password-less VM migration.

### ISSUE THREAD

**Issue by pvital** [kimchi-project/kimchi#1007]
After fill the fields with user and password of the remote server to start a VM migration, a Kimchi error message is prompted but with no description about the backend error:

![screenshot from 2016-09-13 14-16-32](https://cloud.githubusercontent.com/assets/699330/18484034/2552038e-79bd-11e6-80e8-3bce617ba590.png)

The same happens with work-error.log:

```
 KCHVM0068E: Unable to setup password-less login at remote host 192.168.122.1 using user test. Error: 
```

**Comment by danielhb** [comment]
What OS were used in this bug?

**Comment by pvital** [comment]
Ubuntu 16.10 (host) and Fedora 24 (web client)

**Comment by danielhb** [comment]
I guess I wasn't clear enough. What are the OSes of the source and destination? Are you migrating a VM from 2 Ubuntu 16.10 hosts? 

I am asking because, and I know this should be documented better somewhere, there is no support to VM live migration across different distros. At the very least we need the sam versions of both QEMU and libvirt running in both ends - something very unlikely to happen unless you're running the same OS on both source and destination.

**Comment by pvital** [comment]
I don't remember, but I guess the tests were between Ubuntu 16.04 and Fedora 24. That might be the problem here. 

However, a warning can be prompt to user, explaining this requirement and preventing future issues.

**Comment by danielhb** [comment]
Checking out the destination OS and see if it matches the source OS is too expensive and annoying. I think it's better to document the behavior of the feature.

I was able to reproduce this problem migrating a VM from 2 Ubuntu 16 hosts. I'm looking into it.

**Comment by pvital** [comment]
I did not say to check destination OS. Only to warn to user. Like that when user click to reboot, shutdown or power off a VM, or even, in ginger base when user click to reboot or shutdown the host.

Only an informative warning, saying that if the destination OS is different from the source OS, the migration will fail.
