### ISSUE TITLE
Edit template is allowing current cpus to edit greater than the max cpus 

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/kimchi#1068]
Steps to reproduce 
1. Add template 
2. Select template, and click edit from actions 
3. From Processor tab, give Max CPUS as 5, and Current CPUs as 6 
4. Click on Save. 
5. Again edit the same template and you will find the max and current cpus as 6

**Comment by alinefm** [comment]
It is a side effect of a UI change request made in past.
All that because the user almost never clicks on "More" button to get the max vcpus value. So we decided to update the max vcpus value automatically when the user change the vpus value to a greater value than the current max vcpus.
I am not sure this possible to be done, but it would be good to have the 2 input boxes connected. So When the user changes the vCPUs fields to a greater number than max vCPUs, the max vcpus fields is automatically updated to the same vcpus value and then user can only insert a number greater than the vcpus.

**Comment by danielhb** [comment]
I believe this was fixed in recent UI changes I've made, but I'll verify

**Comment by danielhb** [comment]
As I suspected, this was changed by me in commit 6de1a7f82156e0d7c6894c4936bf656c95cf3f57 and it is now fixed in master/stable.
