### ISSUE TITLE
Wok Tab and Missing Icons Debian

### ISSUE THREAD

**Issue by elproducto** [kimchi-project/kimchi#1142]
I noticed the Wok tab and the button to add more guest, storage or network is missin from my recent install of Kimchi on Debian 8.7(Fresh Install).   Any recommended on how to address this?

<img width="1213" alt="screen shot 2017-05-07 at 3 41 51 am" src="https://cloud.githubusercontent.com/assets/3057562/25778839/daf5ebf0-32d7-11e7-831b-590f22c65f49.png">

**Comment by alinefm** [comment]
Wok limits some operations for admin users. Admin users are those with sudo ALL access in the host system.
So if you are not seeing the buttons is because you are not an admin user, ie, you don't have sudo ALL access to the host system. Fixing that will allow you to create guests, networks and pools.

**Comment by elproducto** [comment]
Thank-you that addressed my issue.
