### ISSUE TITLE
Can not create a hard disk

### ISSUE THREAD

**Issue by mwacgi** [kimchi-project/kimchi#1202]
Disk only 10 kb when create / add disk 10 GB.
Ubuntu 16.04.3 /  kimchi 2.5.0

![2017-12-12 19_59_13-wok](https://user-images.githubusercontent.com/16968570/33883636-7c79cb1c-df77-11e7-946b-ecb01521b856.png)
![2017-12-12 20_01_47-novnc](https://user-images.githubusercontent.com/16968570/33883638-8196c8fc-df77-11e7-9a81-523be6533abb.png)

**Comment by genewitch** [comment]
This happens only when "adding storage" to an existing guest. If you make a new template it correctly registers gigabytes.

In my case, i added a new storage pool (disk, DIR, /mnt/ssd01) - and at first i thought it was because i had formatted it with something other than ext4.

Have not seen if this happens on the "default" storage pool. Will check if OP was also using a "new" storage pool other than default.

**Comment by mwacgi** [comment]
This happens also using a "new" storage pool other than default.
![2017-12-19 16_09_57-wok](https://user-images.githubusercontent.com/16968570/34155574-de516f2a-e4f4-11e7-969b-fb92a61633fd.png)
![2017-12-19 16_10_26-novnc](https://user-images.githubusercontent.com/16968570/34155575-df6bbe7e-e4f4-11e7-8d8a-b3a597aaa961.png)

**Comment by sbs20** [comment]
I am also getting this on v2.5.0. It appears to be #1010 again - at least in terms of behaviour if not cause. I managed to create a 1TB by specifying 1073741824.

**Comment by alinefm** [comment]
I will check it later and turn back to you soon.

**Comment by genewitch** [comment]
the commit that "closed" #1010 was reverted, and that's why this is happening again.

**Comment by alinefm** [comment]
Closing this issue as it was fixed by #1228
