### ISSUE TITLE
Future of Kimchi

### ISSUE THREAD

**Issue by githubetc** [kimchi-project/kimchi#1265]
Is Kimchi still being actively developed or maintained ?

It has been a while since the last commit.

**Comment by urbinek** [comment]
up with this question

**Comment by eBeagle** [comment]
Last response I've got was last October. Please see issue #1207.

I'm currently looking at XCP-ng as an alternative.

**Comment by lhorace** [comment]
XCP-ng is a complete alternative, hehehe.

**Comment by githubetc** [comment]
XCP-ng is for Xen ?
Kimchi is for KVM ?
I don't think they are compatible ?

**Comment by lhorace** [comment]
No, there are not, but I think he means a complete different solution to KVM/Web interface, eg XEN/XCP-ng.

**Comment by githubetc** [comment]
I see, thanks for the confirmation.
I guess the search for a Kimchi alternative is still on ...
Or if there is enough interest, may be some users (like me) can work together and help fund a continued maintenance of Kimchi.

**Comment by hardboydu** [comment]
How about ovirt?

**Comment by flayisflay** [comment]
I looked at ovirt and found it to be too sophisticated for my use case. I would probably be more inclined to implement it in an enterprise environment or with a dedicated team than I would be for a small group, or even as an individual (One not trying to build an OG home lab, that is).

My use case for kimchi was within a lab environment at my local hackerspace for use by our classroom. I wanted something which was approachable and had in-browser vnc support to give students an easy mechanism to log in via pam/ldap and access their allocated machine(s) without a complex interface. Additionally, make it easy for an instructor to just jump in rather than spending a lot of time learning the interface (or just requiring one of the admins) to do it.

So far I've looked at proxmox, ovirt, virtmanager, virsh.
I haven't tried the xen ecosystem, and ended up just grabbing a VMware license.

There doesn't seem to be anything else as good as kimchi at solving this particular problem, but I'd be keen to hear it if there are recommendations.

**Comment by lhorace** [comment]
@githubetc  Have a look at https://github.com/cutelyst/Virtlyst, it's not feature rich, however it does get the job for the most part. At least for my use case.

@flayisflay I'm surprise that Proxmox didn't meant your requirements. Compared to Proxmox, VMWare is overkill, and it's free.

**Comment by alinefm** [comment]
Hello everyone!

I've just replied on https://github.com/kimchi-project/kimchi/issues/1207 but I will copy and paste it here so you can have a glue on what happened and what is going to happen.

`I know there has been a long time without a new Kimchi release. That happened because IBM stopped sponsoring Kimchi at the beginning of 2017 and after that, I started a new job and moved to a new country. I needed some time to reorganize myself and get proper attention back to Kimchi. Sorry about that.

But, I will do all I can to keep the project and the community alive. I've just accepted some PRs (and others need to be rebased in order to get accepted) and I am working on make Wok and Kimchi python3 compatible and allow Kimchi to connect to a external libvirt URL rather than the one in which Kimchi is installed. These will be the main features of next Kimchi release.`

**Comment by maikgreubel** [comment]
Hello @alinefm 

this is very surprising! But I'm very happy to read that you are back to support this very usefull piece of software! 

So welcome back and have a lot of fun! :)

**Comment by alinefm** [comment]
I am closing this issue as there are others 2 about the same topic :-) 

Updates on #1278 #1207
