### ISSUE TITLE
 Integrate websockify into cherrypy

### ISSUE THREAD

**Issue by aglitke** [kimchi-project/kimchi#22]
noVNC is supported in Kimchi by launching an external program (websockify.py) to wrap an existing qemu vnc connection with web sockets (needed by noVNC).  This works but has a number of disadvantages:
- Requires a range of ports to be opened through the firewall (to support multiple connections)
- Need to manage and clean up the spawned websockify processes.
- Complex

Anthony proposed an idea to support websocket proxying directly from the cherrypy server on its given port.  The noVNC code would be directed to a URL such as: ws://<host>:8000/vms/vm-1/vnc.  Cherrypy would switch to a websockets handler to service connections at this URL.

**Comment by alinefm** [comment]
Kimchi does not launch an external process for websockify anymore.
Instead of that, Kimchi is relying on python-websockify to enable the websockets connection
(commit 613650d11812aa53fc046b7d573944ca5d3764b3)
Based on that, I don't think this issue makes sense in the current scenario.
I will close it by now, but feel free to reopen if you think anything else can be done on that area.
