### ISSUE TITLE
Some tabs do not ask for login when kimchi restarts

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#376]
1. Start kimchi and open it up in the browser. Log in.
2. Restart kimchi service

If you were in the Guests or Host tabs the login will be prompted automatically without user intervention.
But it does not happen with Template, Storage and Network tabs. Those tabs won't ask for login without manual refresh.

We need to keep a consistent flow in all tabs.

**Comment by cd1** [comment]
So what flow should we use? I'd suggest always redirecting to the login page when the Kimchi session has been interrupted (by stopping or restarting it).

The current - inconsistent - behavior happens because the tabs Host and Guests are constantly sending requests to the server, whereas the other tabs only send requests when there's user interaction. If we want to force every tab to redirect to the login page when there's no connection to the server, the client session should "ping" the server constantly in a way that won't overload the server when many users are logged in.
