### ISSUE TITLE
Windows XP: Kimchi should set the right NIC Type in Templates

### ISSUE THREAD

**Issue by magnusboman** [kimchi-project/kimchi#604]
It'd be nice if one could specify which NIC type to be used for a virtual machine. As an example, Windows XP doesn't recognize virtio or e1000, but it does recognize pcnet.

**Comment by alinefm** [comment]
@magnusboman This kind of information is for expert users. As the main focus of Kimchi is the entry level users I don't think it is a good idea to let the user takes that decision.

Otherwise, Kimchi must be smart enough to get the right values to allow user creates any virtual machine. From your example, Kimchi should automatically pick up pcnet as the NIC type when using Windows XP.

Could you, please, confirm what are the NIC types supported by each Windows version? So we can properly configure Kimchi to do the right thing.

**Comment by magnusboman** [comment]
I've tested with WinXP, Win7, Win8 and Win10. Of them, only WinXP need a different NIC (pcnet)
