### ISSUE TITLE
HA/Host Clustering

### ISSUE THREAD

**Issue by TheGuyDanish** [kimchi-project/kimchi#640]
Just a suggestion, and please do tell me if this is something you have in mind. But something like a system to manage more Kimchi installations from one centralized location would be amazing.

**Comment by laggarcia** [comment]
@TheGuyDanish, Kimchi currently has a feature that permits it to connect to other Kimchi server running on the same subnet through the peers button on the top of the screen. If you select another peer, you'll start to see the Kimchi interface of that other server.

Is this sufficient for what you are looking for or do you want to see all Kimchi servers information on the screen at the same time?

**Comment by TheGuyDanish** [comment]
@laggarcia I don't see the peers button that you're speaking of, but I was thinking of something like a centralized management solution, where you could log on to one interface, then immediately be able to take care and handle all your Kimchi installs.

**Comment by cd1** [comment]
That peers button is not displayed by default because it needs extra dependencies and configuration. Take a look at the file `docs/README-federation.md` for more information on how to enable it.

When federation is enabled, you'll see a new button on the top right corner of the screen which will list all the other federation-enabled Kimchi servers in your network (i.e. you need to enable federation to the other peers as well, otherwise the list will be empty). Clicking on each server URL will open a new window so you can manage that server.

However, handling multiple Kimchi servers from one single interface isn't possible yet. We have plans to add that in the future.

**Comment by alinefm** [comment]
Just a correction: we don't have plans to have a centralized interface to manage multiple Kimchi instances.
We've already had the federation features which can list the Kimchi peers in the same network but each Kimchi instance has it own interface.
We have plans to extend the peers management, so user can manually add/remove peers from other sub-networks.
