### ISSUE TITLE
Hide guest restart button when guest is offline

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#649]
In order to make UI simpler, I would like to propose to hide the restart button when the VM is offline.
Today it is disabled.

**Comment by cd1** [comment]
[This post on User Experience Stack Exchange](http://ux.stackexchange.com/questions/34271/greyed-out-vs-invisible) discusses this very behavior. Please take a moment to read it.

According to the discussion above, which I agree with the accepted answer, a UI element should be hidden if the user cannot make it visible with a direct action, and it should be disabled if the user can enable it by performing some action. In other words, the element should be hidden if there's nothing (or not much) the user can do to activate it (so they don't need to about the element), or it should be disabled if the action isn't available at that moment but it can become available if the user performs some action (so they know the element exists but it cannot be used at that moment only).

So, IMO, the button "Restart" (and also "Pause/Resume", when it becomes available) should remain disabled if it cannot be clicked on, because it _can_ become enabled if the user starts the VM on that same page. And especially in the case of the button "Restart", which is the first button on that row, if it keeps getting hidden and visible, the button row will either need to be shifted left and right several times or it will contain "holes" in "random" places. And none of those approaches looks good to me.

As another example, our element "Peers", at the top right corner of the page, is completely hidden when the user cannot use that feature because it will not become available at all, no matter what the user does - the server configuration must be changed and it must be restarted in order to activate the peers feature, and the user cannot do that. When the server has the peers feature enabled, however, the element "Peers" is visible. This is a different use case than the "Restart" (and "Pause/Resume") button.

**Comment by alinefm** [comment]
Closing based on last comment.
