### ISSUE TITLE
Repository variables not replaced with their values

### ISSUE THREAD

**Issue by cd1** [kimchi-project/kimchi#662]
When I go to the repositories list on the tab "Host", the repositories' names have variables on their names instead of their corresponding values.

I'm running Fedora 22, Kimchi 30ceeea32b3913e09cb7082c4d90022a47594d01, Chrome 43.0.2357.81 (64-bit).

## How to reproduce ##

1. Install and start Kimchi.
2. Log in with an admin user (e.g. `root`).
3. Switch to the tab "Host" and scroll down to the section "Repositories".

## Actual behavior ##

After step (3), the repositories' names are displayed with variable names inside. One sample name is:

```
Fedora $releasever - $basearch
```

## Expected behavior ##

After step (3), the repositories' names should be displayed with the correct values instead of their variable names.

**Comment by danielhb** [comment]
I've discussed this with cd1 about a week ago and I believe it is worth discussing it here.

In my opinion, the variables in the repositories names and links shouldn't be resolved. Let me give an example. This is the default repository of Fedora:

-----------
[fedora]
name=Fedora $releasever - $basearch
failovermethod=priority
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
-------------

Notice that this is the same repo for multiple Fedora distros. In the case you run F21, the metalink will replace $releasever with '21'. The YUM API makes this replacement and the repository feature in  Kimchi showed that way. This lead to a handful of problems:

- The user does not have a clue that the '21' is a variable resolve because the UI didn't provide any indicator that give a hint about it

- When looking in the fedora.repo file the user might wonder why the repository does not have any '21' but a lot of ${releasever} strings. 

- when saving a repository in Kimchi back in the YUM API times, 2 things might occur: it does not overwrite the variable, which is misleading to the user. Or it does overwrite the variable, replacing all
the {releasever} with '21' and then the user will wonder why his repositories stopped working when doing a distro up to Fedora 22.

This is my case of why the variables shouldn't be resolved at all. Kimchi is not aimed for the average grandma that uses Facebook in IE. It is expected that the Kimchi user (a user that has 'sudo' privileges) understands what these variables in the repository info are for and, if he decides to change them, he knows exactly what he is doing.

**Comment by laggarcia** [comment]
@danielhb, I disagree with your point.

We are showing this information on the UI. The user is not reading a configuration file. The UI should show the information as clear as possible to a user. In this case, that would mean we should calculate the values of the variables and show something the user could actually read and understand easily.

If the user selects to edit this value, then I agree with you that we need to reload them to show the variables so that the user can properly edit them. After doing that, we need to reload the values again with the variables solved in the table.

Also, I disagree with your last point as well. Kimchi is aimed to be easy to use. I agree that, if someone wants to edit the repository, they would need to know what they are doing, and that's why I think, in this specific case, we need to show the variables. But while only reading the screen, the user should be able to get some value add for Kimchi. Otherwise, they would go read the configuration file directly.

**Comment by alinefm** [comment]
Fixed by e3613efbca8ca284eb2a84d24e404c1a1b5adb3f
