### ISSUE TITLE
openSUSE: problem while building Kimchi

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#670]
"make install" fails on openSUSE 13.2 with the following error:

make[2]: Entering directory '/root/kimchi'
make[2]: Nothing to be done for 'install-exec-am'.
touch /root/kimchi/tmp//var/lib/kimchi/objectstore
mkdir -p /root/kimchi/tmp//var/log/kimchi/
touch /root/kimchi/tmp//var/log/kimchi/kimchi-access.log
touch /root/kimchi/tmp//var/log/kimchi/kimchi-error.log
mkdir -p /root/kimchi/tmp//etc/kimchi/
/usr/bin/install -c -m 644 src/dhparams.pem /root/kimchi/tmp//etc/kimchi/dhparams.pem
touch /root/kimchi/tmp//etc/nginx/conf.d/kimchi.conf
touch: cannot touch ‘/root/kimchi/tmp//etc/nginx/conf.d/kimchi.conf’: No such file or directory
Makefile:975: recipe for target 'install-data-local' failed
make[2]: *** [install-data-local] Error 1
make[2]: Leaving directory '/root/kimchi'
Makefile:789: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/root/kimchi'
Makefile:494: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

Also the "make rpm" fails with a different error:

make[3]: Leaving directory '/root/kimchi/rpm/BUILD/kimchi-1.5.0'
make[2]: Leaving directory '/root/kimchi/rpm/BUILD/kimchi-1.5.0'
make[1]: Leaving directory '/root/kimchi/rpm/BUILD/kimchi-1.5.0'
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-suse
Processing files: kimchi-1.5.0-0.noarch
error: File not found: /root/kimchi/rpm/BUILDROOT/kimchi-1.5.0-0.x86_64/etc/init.d/kimchid

RPM build errors:
    File not found: /root/kimchi/rpm/BUILDROOT/kimchi-1.5.0-0.x86_64/etc/init.d/kimchid
Makefile:956: recipe for target 'rpm' failed
make: *** [rpm] Error 1

**Comment by ramonmedeiros** [comment]
Please, assign to me

**Comment by ramonmedeiros** [comment]
Hi Aline,

make install worked for me. Only make rpm broke because the spec is waiting for /etc/init.d/kimchid, but, openSuSE 13.2 uses systemctl. Applying this fix seems to solve make rpm issue:

diff --git a/contrib/kimchi.spec.suse.in b/contrib/kimchi.spec.suse.in
index fa55cc5..b85b516 100644
--- a/contrib/kimchi.spec.suse.in
+++ b/contrib/kimchi.spec.suse.in
@@ -41,6 +41,11 @@ BuildRequires:	python-lxml
 Requires:       python-ordereddict
 %endif
 
+%if 0%{?suse_version} >= 1210
+BuildRequires: systemd-rpm-macros
+%{?systemd_requires}
+%endif
+
 %description
 Web server application to manage KVM/Qemu virtual machines
 
@@ -56,10 +61,29 @@ rm -rf %{buildroot}
 make DESTDIR=%{buildroot} install
 
 %post
-chkconfig kimchid on
+%if 0%{?suse_version} >= 1320
+    %service_add_post kimchid.service
+%else
+    chkconfig kimchid on
+%endif
+exit 0
+
 
 %preun
-service kimchid stop
+%if 0%{?suse_version} >= 1320
+    %service_del_preun kimchid.service
+%else
+    service kimchid stop
+%endif
+exit 0
+
+
+%postun
+%if 0%{?suse_version} >= 1320
+    %service_del_postun kimchid.service
+%endif
+exit 0
+
 
 %clean
 rm -rf $RPM_BUILD_ROOT
@@ -94,7 +118,6 @@ rm -rf $RPM_BUILD_ROOT
 %{_sysconfdir}/kimchi/distros.d/ubuntu.json
 %{_sysconfdir}/kimchi/distros.d/gentoo.json
 %{_sysconfdir}/kimchi
-%{_initrddir}/kimchid
 %{_sysconfdir}/kimchi/
 %{_var}/lib/kimchi/debugreports/
 %{_var}/lib/kimchi/screenshots/
@@ -105,6 +128,13 @@ rm -rf $RPM_BUILD_ROOT
 %{_localstatedir}/log/kimchi/
 %{_mandir}/man8/kimchid.8.gz
 
+%if 0%{?suse_version} >= 1320
+%{_unitdir}/kimchid.service
+%else
+%{_initrddir}/kimchid
+%endif
+
+
 %changelog
 * Thu Feb 26 2015 Frédéric Bonnard <frediz@linux.vnet.ibm.com> 1.4.0
 - Add man page for kimchid
