### ISSUE TITLE
What's the spice address of a VM which can be used in virt-viewer?

### ISSUE THREAD

**Issue by J-F-Liu** [kimchi-project/kimchi#712]
virt-viewer can be downloaded from http://virt-manager.org/download/

**Comment by alinefm** [comment]
Hi @J-F-Liu!

virt-viewer uses the console address configure in the guest XML.
To use virt-viewer you don't need to specific any address, you need to specific the guest name.
Example: virt-viewer <my-guest-name> and it will properly handle the console configure in the guest XML.

Hope it helps.

Let me know if we can close this issues.

**Comment by TravisCHoward** [comment]
I think he's asking how we can use virt-viewer on a remote machine to connect to a guest. I am also having this issue. On a remove machine I've tried connecting to "spice://[the-IP]:5900" to no avail. I cannot find information anywhere. The built-in SPICE viewer is crap for Windows guests and I need to use virt-viewer remotely as my server is headless. What do I do?

**Comment by J-F-Liu** [comment]
Yes, @TravisCHoward clarifies my question.

**Comment by alinefm** [comment]
Hi @TravisCHoward ! Hi @J-F-Liu !

For security matters, while creating a guest using Kimchi, the guest console connection will point to localhost. That way, we force user to connect to Kimchi to have access to the guest console.
Otherwise, the user need to have access to the host system.

You can check the guest XML:
<graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1'>

So you need to use the host IP as a gateway to access the guest console.
I don't know how to do that for spice, but using vncviewer, you would need to do:

vncviewer -via <HOST-IP> localhost:0

Hope it helps.

**Comment by alinefm** [comment]
I will close this issue due inactivity. Please, reopen if any further help on it is needed.
