### ISSUE TITLE
Suggested changes to installation instructions

### ISSUE THREAD

**Issue by mcvax** [kimchi-project/kimchi#750]
Hi,

Can I suggest a few changes to the installation instructions here: https://github.com/kimchi-project/kimchi

The instructions for installing the plugins lists this command:

    $ git clone --recursive https://github.com/kimchi-project/wok.git

But I think it should instead be:

    $ git clone --recursive https://github.com/kimchi-project/kimchi.git

The page also says to use the command:

    $ git submodule init

However on Centos7 I receive an error:

    You need to run this command from the toplevel of the working tree.

Finally, it doesn't mention anywhere that once you have cloned the plugins in the source tree you need to run these commands from the plugin source directory:

    $ ./autogen.sh --system
    $ make
    $ sudo make install

**Comment by mcvax** [comment]
The dependencies also now appear to require python-magic

    yum python-magic

**Comment by alinefm** [comment]
Hi @mcvax 

The --recursive option on git-clone is to clone the git-submodules associated to a given repository.
Kimchi does not have any git-submodule but Kimchi *is* a git-submodule of Wok project.
Because that, the instructions guide user to use git-clone --recursive on Wok repository.

About python-magic, it is already listed as required in the documentation and package build process.

I will close this issue by now but feel free to reopen on any news.
