### ISSUE TITLE
Change boot order

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/kimchi#828]
Allow user change boot order in the guest configuration.

**Comment by derdigge** [comment]
is there a way? editing a file or so to allready change bootorder?

**Comment by alinefm** [comment]
Hi @derdigge 

You will need to manually edit the guest XML or wait for this feature gets available on Kimchi =)

**Comment by derdigge** [comment]
Thanks!

I was mit able to locate them in my  own. Where is the location?

**Comment by ramonmedeiros** [comment]
Just add this feature at hash: 42717b3fd98e4d40f75be4cc515fbec9d05a74c7

**Comment by ramonmedeiros** [comment]
You can test by REST API

**Comment by pvital** [comment]
The solution (backend part) is already upstream by the commits https://github.com/kimchi-project/kimchi/commit/e05c7a378ba4302047ebc12142ed850e1215ad7c https://github.com/kimchi-project/kimchi/commit/a5b9e1fd8f34d6886bc3874b9f4f1dd45ddac613 https://github.com/kimchi-project/kimchi/commit/394422f11cc99b9cc9dbad4e4ea1920020dcaa4b https://github.com/kimchi-project/kimchi/commit/7d6be682ab01fadd2590a9af7ea199749a85a086 https://github.com/kimchi-project/kimchi/commit/255e6d90c7bf756798054940bdf71924971f16aa https://github.com/kimchi-project/kimchi/commit/42717b3fd98e4d40f75be4cc515fbec9d05a74c7 , and since UI is being addressed by issue #979, I guess this one can be closed.
