### ISSUE TITLE
[UI] Save button is having wrong behavior when edit a running Guest

### ISSUE THREAD

**Issue by Truja** [kimchi-project/kimchi#847]
Create a guest and start it.
Then open the Edit window:
- You will be in General tab and Save button will be enabled;
- Move to other tabs: Save button is going to be disabled and enabled again, depending on where you was and are.
- You ended up having the button always disabled in General tab.

**Comment by samhenri** [comment]
I'm working on enabling the Save button when switching back to General tab but as for the other tabs the button is disabled because the changes are saved by default when the user changes them on each tab. In the old-ui the button would simply disappear but I thought it wouln't look consistent with the other screens.

**Comment by sstoppler** [comment]
Can you please take a look at this?  Another problem seen with the Save button which may be related is the following:

When we edit an Guest for adding PCI devices , the necessary changes are not instantly reflected in GUI, neither the Save button is enabled to apply the changes.

The changes in the device that are added/removed from the guest, are reflected in the Guest's XML file, which can be verified from the host.

== Steps to Reproduce ==
1. Select the "Edit" option under Actions for the particular guest(shut-down state).

2. Go to the Tab "Pci" , and select the device to be added to the guest by clicking the Power button.
The device gets added in the guest XML file, which can be verified from the host.

However from the GUI , there is no change in the particular device entry neither the Save button is enabled.

**Comment by samhenri** [comment]
Hi, the save button for tabs that have inline editing is disabled by default because the actions are done in each row. We can change that in the future but for now I think we should put a feedback message  

I've updated the table once a device is enabled or disabled but right now I'm unable to test it here. I'm going to test in a different machine that has VT-x enabled

**Comment by samhenri** [comment]
Just sent a patch to the mailing list
