### ISSUE TITLE
Peers button disappears

### ISSUE THREAD

**Issue by finish06** [kimchi-project/kimchi#921]
Issue: when i click the peers downward arrow, it immediately disappears, no dialogue box opens.

Tried the following to ensure everything in federation was set up correctly - SUCCESS. KVMhost1 finds KVMhost3
`curl -u <user:password> -H "Content-Type: application/json" -H "Accept: application/json" -k https://localhost:8001/plugins/kimchi/peers`

No errors show in Firebug for JS.  The information appears to be present, the UI is just not responding appropriately.

**Comment by samhenri** [comment]
I can send a patch to fix the missing drop-down button, HOWEVER, if the user remains on a Wok tab or a Ginger tab, the browser JavaScript console will throw an error message saying that kimchi is not defined, as kimchi.min.js and ginger and gingerbase js files are only loaded when one of these plugins is active.
My recommendation is to move the peers function and API to Wok or move to a panel instead of using the navbar or toolbar for it. @alinefm how should we proceed?

**Comment by samhenri** [comment]
Hi, I can't enable federation on my environment so I need a JSON with a list of peers
