### ISSUE TITLE
Unable to assign pci passthrough devices through kimchi

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#956]
Issue:
Nothing happens when clicking on the little icon beside any of the pci adapters when trying to add to a guest

Notes from @Truja 
PCI Passthrough has changed in Kimchi backend, it uses async tasks now to attach (POST request) and detach (DELETE request) and UI did not follow this change.

UI must be fixed to retrieve information from the task.
Also would be good to add a 'loading' icon while the task does not finish.

**Comment by samhenri** [comment]
Hi, I'm working on it but I'm facing some issues when trying to enable a device so I have some questions:

1) When I try to enable a device I receive the following error:
```{
    "status":"failed",
    "message":"KCHVMHDEV0003E: No IOMMU groups found. Host PCI pass through needs IOMMU group to function correctly. Please enable Intel VT-d or AMD IOMMU in your BIOS, then verify the Kernel is compiled with IOMMU support. For Intel CPU, add 'intel_iommu=on' to GRUB_CMDLINE_LINUX parameter in /etc/default/grub file. For AMD CPU, add 'iommu=pt iommu=1'.",
    "id":"1",
    "target_uri":"/plugins/kimchi/vms/ubuntu15.10-vm-1/hostdevs/"
  }```

But I do have intel_iommu=on and even tried with iommu=1 and the error persists.

2) If I could filter by device name I could put a loading icon on the Enable / Disable button for each activating device however since I can't get any device to enter in "running" status, I can't call getTaskByFilter. I'm not even sure If I can filter the tasks by:
```var filter = 'status=running&target_uri=' + encodeURIComponent('^/plugins/kimchi/vms/' + kimchi.selectedGuest+ '/hostdevs');```. Can someone send me a JSON with the expected output? In other scenarios like this I could filter by name, in this case I think I need the device name that is sent with POST with ```{ name: device }```.

3) I'm not sure why but the device status is checked by the CSS icon class on the button. How can I check if a device is really enabled or disabled?

**Comment by jrziviani** [comment]
Hello @samhenri 

Don't know if you're aware of PCI Passthrough so here we go with a too simple overview and the requirements itself.

### Intro

Not all computer devices are _'easy'_ to virtualize like CPU and memory, devices like network cards are specially hard to share its "pieces" between the host and its VMs. For this reason softwares have been written to address this gap, allowing network packets to find the right route to the right VM or host. It works good, except if you need your VM to experience the full performance provided by your network card without the overhead necessary to handle multiple network connections using just one card.

For this reason we have PCI passthrough. Suppose my system has 2 network cards, I can assign the first one to the host and choose my _performance hunger_ VM to use (exclusively) that other one.

To know more: https://www.ibm.com/developerworks/library/l-pci-passthrough/

### What does this screen do?

The goal is to list all PCI devices that can be assigned to a VM, each device has a button on the right. If a particular device is not attached you click on it to be attached, if it's attached you click on it to detach.

![image](https://cloud.githubusercontent.com/assets/670087/16861450/27660132-4a17-11e6-80e1-c9970c3f4a15.png)
device not attached, if I click on the right icon it state changes to

![image](https://cloud.githubusercontent.com/assets/670087/16861465/57f642e4-4a17-11e6-97a5-de1e54623802.png)
the green image on the left is just a sign to let users know this device is attached. If you click on the right icon again it should go back to the first state - detaching the device.

### What's the problem?

**Before backend using tasks**: User clicks "attach/detach", UI sends request to backend and wait until it finishes. UI then refreshes the list, where a field tells it was attached (or detached).

**Today**: User clicks "attach/detach, UI sends request to backend and wait BUT the backend will return a task number. The UI refreshes the list but nothing will be updated because the attachment is still running.

### What do we need?

After receiving the the response from backend, poll the task until it finishes. Then UI can refresh the list.

### Answers

1. let's try to debug your problem via IRC, I was able to make it work here.
2. some examples:
    **method:** POST
    **uri:** https://host:8001/plugins/kimchi/vms/test/hostdevs
    **body:** {"name": "pci_0002_01_00_0"}

    **returns:**
    ```{
      "status":"running",
      "message":"Attaching PCI device",
      "id":"1",
      "target_uri":"/plugins/kimchi/vms/test/hostdevs/"
    }```

    **method:** GET
    **uri:** https://host:8001/plugins/kimchi/tasks/1

    **returns:**
    ```{
      "status":"finished",
      "message":"OK",
      "id":"1",
      "target_uri":"/plugins/kimchi/vms/test/hostdevs/"
    }```

    **method:**: DELETE
    **uri:** https://host:8001/plugins/kimchi/vms/test/hostdevs/pci_0002_01_00_0

    **returns:**
    ```{
      "status":"running",
      "message":"Detaching device.",
      "id":"4",
      "target_uri":"/plugins/kimchi/vms/test/hostdevs/pci_0002_01_00_0"
    }```
3. look this code:

```javascript
    var setupPCIDevice = function() {
        kimchi.getAvailableHostPCIDevices(function(hostPCIs) {
            kimchi.getVMPCIDevices(kimchi.selectedGuest, function(vmPCIs) {
                setupNode(hostPCIs, 'fa-power-off');
                setupNode(vmPCIs, 'fa-ban');
            });
        });
```
hostPCIs, got from getAvailableHostPCIDevices(), has all PCIs attached to the host, the real hardware.
vmPCIs, got from getVMPCIDevices(), has all PCIs (if any) attached to a particular VM.

So, this code basically set all devices with 'detached' icon, then it goes to all devices attached to that VM changing the icon to 'attached'.

Hope it helps, ask me if anything.

**Comment by samhenri** [comment]
Ok, but when the user clicks any button to attach a device and I start polling tasks running, should I prevent the click from other buttons and put a "loading" icon on all of them?
If I could filter the device name from the GET task url then I could disable only this specific device and allow user to click the other buttons, even if it only allows attaching one device at the time at least I can create a queue on the front-end for this.
Right now the task ID only returns the ```"vm_name/hostdevs/"```, I know that one device is being attached but not which one is it and therefore the PCI devices lists will be blocked until this task is finished. I could disable the button after the user has clicked and enable the other buttons but this button state would be lost if the user closed the modal window, reloaded the tab or logged out.

**Comment by Brainiarc7** [comment]
@samhenri , ensure that your IOMMU device groups are valid.

Run:

`for iommu_group in $(find /sys/kernel/iommu_groups/ -maxdepth 1 -mindepth 1 -type d); do echo "IOMMU group $(basename "$iommu_group")"; for device in $(ls -1 "$iommu_group"/devices/); do echo -n $'\t'; lspci -nns "$device"; done; done`

And see the output it provides.
If you get no output,  you either have not enabled IOMMU support properly or your hardware does not support it. 

Secondly, on assigning the PCI devices for passthrough, do you use the pci-stub (legacy, pre-4.1-linux method) or the newer vfio-pci module (post-4.1 linux module) version?

**Comment by samhenri** [comment]
@Brainiarc7 the output is empty. Is it possible to emulate IOMMU on nestesd VMs?

**Comment by Brainiarc7** [comment]
Yes, what is your CPU's make?

**Comment by samhenri** [comment]
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                20
On-line CPU(s) list:   0-19
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz
Stepping:              2
CPU MHz:               3096.730
CPU max MHz:           3500.0000
CPU min MHz:           1200.0000
BogoMIPS:              6199.53
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-19
```

**Comment by samhenri** [comment]
Hi, I'm sending a patch to the ML however I wasn't able to test the success calls, only the progress and error when attaching a device. When detaching a new device, I've noticed that on vmhostsdev.py when detaching a PCI device there are the following messages:
-Detaching device. (I've removed the dot in the end just to keep consistency with other messages)
-Updating MMIO from VM...
-Detaching device from VM...
-Deleting affected PCI devices...
-Updating MMIO from VM...
 
Does these messages keep changing on the "message" key from the task until is fails or succeeds? Right now I'm only checking for the exacy string "Detaching device" and "Attaching device" to keep looping and going into the progress callback. If the patch I'll send works then I'm ok.

**Comment by samhenri** [comment]
Patch sent to ML.

**Comment by jrziviani** [comment]
I'm testing it

**Comment by sstoppler** [comment]
There were other issues encountered that Ziviani is finishing up as Samuel is on vacation.
