### ISSUE TITLE
Change mouse pointer to "loading"/"thinking" in each request or user action

### ISSUE THREAD

**Issue by sstoppler** [kimchi-project/kimchi#966]
New Kimchi/Wok/Ginger interface does not allow user to know what is going on in some interactions, like passthrough. 
If user clicks on some button to perform some action, or open some modal window,  there is no way to know if something is happening. 
In interactions where UI is waiting request response from backend, there should be an indication of that.

Feedback is that in previous version it was easier to understand what was happening and that helped in tests.

**Comment by samhenri** [comment]
I think we can tackle this with a change in wok.requestJSON that should apply to every asynchronous request however I think we should keep the "pointer" cursor for links and buttons. It would also make cursor change every second from 'auto' style to 'progress' in Guests when the VMs are refreshing and with the notifications.

**Comment by alinefm** [comment]
Duplicated of #214

**Comment by samhenri** [comment]
After inspecting some functions I concluded that this won't be an easy task and would require changes in Wok and all plugins. On Wok it would require a new CSS class to change the cursor but keeping the links and button elements with the pointer cursor intact. The disabled elements should keep the "not-allowed" icon instead of showing the progress icon.
Dealing with this on wok.requestJson is not a good idea as it would flick the cursor every notification call or guests list refresh. We would have to add a class to html or body tags on each "running" block from the onTaskResponse() from all plugins. I could set this by default on this function but it won't show the loading cursor unless each asynchronous call uses the trackTask() function.

**Comment by samhenri** [comment]
Patch sent to all mailing lists (Wok, Kimchi, Ginger and Gingerbase). For now it only works with user actions that calls kimchi.trackTask() and have a "progress" callback, it can be seen with PCI devices after #956 is fixed and with Volume Management.

**Comment by sstoppler** [comment]
Patch applied upstream:  https://github.com/kimchi-project/kimchi/commit/eb3864f1a774a02406bf3a04ac69b1f91914d1f6
