### ISSUE TITLE
Pointer is mismatching on win_10 and win2012 server with spice and vnc

### ISSUE THREAD

**Issue by derdigge** [kimchi-project/kimchi#967]
Dear Mr. Kimchi ;)

I am facing following issue when handling windows guests. The Mouse Pointer position is mismatching and its hard to hit the buttons. This is very annoying during installation and makes it hard.

I found this one:
https://github.com/kanaka/noVNC/issues/131

They are facing this issue with:
--usbdevice tablet

I really like the simplicity of kimchi and don't want to drive a full blown opennebula for example to face this issue.

Thanks!
derdigge

**Comment by danielhb** [comment]
@derdigge thanks for reporting this issue. We can try to fix it in noVNC side, although there is a fix of ours (https://github.com/kanaka/noVNC/pull/596) sent April 11th that they are yet to accept. There's no guarantee of whether they will accept or when. So we can't realistic expect a quick fix from their side, even if we help.

Have you tried using Spice instead of noVNC to connect to this WIndows guest? Perhaps the problem does not exist there.

Also, I am working in a Kimchi feature that will allow VM connections using virt-viewer (the VNC desktop app) that is more stable than the web-clients of vnc/spice. I believe this will be a good alternative. If you want to keep track of this development see https://github.com/kimchi-project/kimchi/issues/944

Daniel

**Comment by derdigge** [comment]
Hi and Thanks for that hint.

It does not matter if i use spice or vnc. What works, is using a local spice client (instead of the Browser one) because it catches your mouse pointer. You need to move the mouse much farer than on You normal Desktop but it does.

No idea if that behavior is same for linux guests?

**Comment by danielhb** [comment]
This behavior tends do vary between guest OS. I experience lots of mouse pointer problems with Opensuse guests, but Fedora and Ubuntu usually works fine.

The feature I've mentioned would give the choice to use the local spice/vnc client without having to setup it manually. You download a launch script and then double-click it, virt-viewer (Remote Desktop Viewer or whatever default VNC/Spice desktop app you have) opens up automatically opens the session for you. It's not a solution for the bug you've described but it's a more convenient way to fall back to the desktop client when needed.

**Comment by alinefm** [comment]
Is it duplicated of #651 ?

**Comment by alinefm** [comment]
Closing as duplicated of #651 
Please, reopen if necessary.
